name: attributions

on:
  push:
    branches:
      - main

jobs:
  update-attributions:
    if: github.actor != 'github-actions[bot]'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Use Node.js 22.x
        uses: actions/setup-node@v5
        with:
          node-version: 22
          cache: 'npm'
      - name: Install npm deps
        run: npm ci
      - name: Regenerate ATTRIBUTIONS.md
        run: npm run report:licenses
      - name: Commit updated ATTRIBUTIONS.md
        run: |
          if git diff --quiet ATTRIBUTIONS.md; then
            echo "ATTRIBUTIONS.md is up to date";
            exit 0;
          fi
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add ATTRIBUTIONS.md
          git commit -m "chore: update attributions"
          git push
