name: chrome-store-upload

permissions:
  contents: read

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  upload-chrome-webstore:
    runs-on: ubuntu-latest
    if: >
      github.event_name == 'workflow_dispatch' ||
      (github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.repository)
    steps:
      - uses: actions/checkout@v5
      - name: Use Node.js 22.x
        uses: actions/setup-node@v5
        with:
          node-version: 22
          cache: 'npm'
      - name: Install npm deps
        run: npm ci
      - name: Build extension for Chrome
        run: npm run build
      - name: Zip Chrome build output
        run: |
          cd build
          zip -r ../icloud-hide-my-email-chrome-extension.zip .
      - name: Upload to Chrome Web Store
        uses: mobilefirstllc/cws-publish@latest
        with:
          action: 'upload'
          client_id: ${{ secrets.CHROME_CLIENT_ID }}
          client_secret: ${{ secrets.CHROME_CLIENT_SECRET }}
          refresh_token: ${{ secrets.CHROME_REFRESH_TOKEN }}
          extension_id: ${{ secrets.CHROME_EXTENSION_ID }}
          zip_file: icloud-hide-my-email-chrome-extension.zip
