name: Release for Chrome, Firefox, and Edge

on:
  workflow_dispatch:

jobs:
  version:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    outputs:
      extension_version: ${{ steps.package-version.outputs.extension_version }}
    steps:
      - uses: actions/checkout@v5
      - name: Extract extension version
        id: package-version
        run: |
          VERSION="$(node -p "require('./package.json').version")"
          echo "extension_version=${VERSION}" >> "$GITHUB_OUTPUT"
  
  build-chrome-and-edge:
    permissions:
      contents: read
      actions: write
    runs-on: ubuntu-latest
    needs: version
    steps:
      - uses: actions/checkout@v5
      - name: Use Node.js 22.x
        uses: actions/setup-node@v5
        with:
          node-version: 22
          cache: 'npm'
      - name: Install npm deps
        run: npm ci
      - name: Build extension for Chrome
        run: npm run build
      - name: Zip Chrome build output
        run: |
          cd build
          zip -r ../icloud-hide-my-email-plus-chrome-extension.zip .
      - name: Duplicate Chrome build for Edge
        run: cp icloud-hide-my-email-plus-chrome-extension.zip icloud-hide-my-email-plus-edge-extension.zip
      - name: Upload Chrome artifact
        uses: actions/upload-artifact@v4
        with:
          name: icloud-hide-my-email-plus-chrome-extension
          path: icloud-hide-my-email-plus-chrome-extension.zip
      - name: Upload Edge artifact
        uses: actions/upload-artifact@v4
        with:
          name: icloud-hide-my-email-plus-edge-extension
          path: icloud-hide-my-email-plus-edge-extension.zip

  build-firefox:
    permissions:
      contents: read
      actions: write
    runs-on: ubuntu-latest
    needs: version
    steps:
      - uses: actions/checkout@v5
      - name: Use Node.js 22.x
        uses: actions/setup-node@v5
        with:
          node-version: 22
          cache: 'npm'
      - name: Install npm deps
        run: npm ci
      - name: Build extension for Firefox
        run: |
          npm run build:firefox
          npx web-ext lint --source-dir build
          npx web-ext build --source-dir build --artifacts-dir . --filename icloud-hide-my-email-plus-firefox-extension.zip
      - name: Upload Firefox artifact
        uses: actions/upload-artifact@v4
        with:
          name: icloud-hide-my-email-plus-firefox-extension
          path: icloud-hide-my-email-plus-firefox-extension.zip

  publish-chrome:
    permissions:
      actions: read
    runs-on: ubuntu-latest
    needs: build-chrome-and-edge
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: icloud-hide-my-email-plus-chrome-extension
          path: artifacts
      - name: Publish to Chrome Web Store
        uses: mobilefirstllc/cws-publish@latest
        with:
          action: publish
          client_id: ${{ secrets.CHROME_CLIENT_ID }}
          client_secret: ${{ secrets.CHROME_CLIENT_SECRET }}
          refresh_token: ${{ secrets.CHROME_REFRESH_TOKEN }}
          extension_id: ${{ secrets.CHROME_EXTENSION_ID }}
          zip_file: artifacts/icloud-hide-my-email-plus-chrome-extension.zip

  publish-firefox:
    permissions:
      actions: read
    runs-on: ubuntu-latest
    needs: build-firefox
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: icloud-hide-my-email-plus-firefox-extension
          path: artifacts
      - name: Publish to Firefox Add-ons
        uses: wdzeng/firefox-addon@v1
        with:
          addon-guid: ${{ secrets.FIREFOX_ADDON_GUID }}
          xpi-path: artifacts/icloud-hide-my-email-plus-firefox-extension.zip
          self-hosted: false
          jwt-issuer: ${{ secrets.FIREFOX_JWT_ISSUER }}
          jwt-secret: ${{ secrets.FIREFOX_JWT_SECRET }}

  publish-edge:
    permissions:
      actions: read
    runs-on: ubuntu-latest
    needs: build-chrome-and-edge
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: icloud-hide-my-email-plus-edge-extension
          path: artifacts
      - uses: wdzeng/edge-addon@v2
        with:
          product-id: ${{ secrets.MICROSOFT_PRODUCT_ID }}
          zip-path: artifacts/icloud-hide-my-email-plus-edge-extension.zip
          api-key: ${{ secrets.MICROSOFT_API_KEY }}
          client-id: ${{ secrets.MICROSOFT_CLIENT_ID }}

  create-release:
    permissions:
      contents: write
      actions: read
    runs-on: ubuntu-latest
    needs:
      - build-chrome-and-edge
      - build-firefox
      - version
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: icloud-hide-my-email-plus-chrome-extension
          path: artifacts
      - name: Download Edge artifact
        uses: actions/download-artifact@v4
        with:
          name: icloud-hide-my-email-plus-edge-extension
          path: artifacts
      - name: Download Firefox artifact
        uses: actions/download-artifact@v4
        with:
          name: icloud-hide-my-email-plus-firefox-extension
          path: artifacts
      - name: Create GitHub release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ needs.version.outputs.extension_version }}
          name: v${{ needs.version.outputs.extension_version }}
          body: |
            Automated release for version v${{ needs.version.outputs.extension_version }}
          files: |
            artifacts/icloud-hide-my-email-plus-chrome-extension.zip
            artifacts/icloud-hide-my-email-plus-edge-extension.zip
            artifacts/icloud-hide-my-email-plus-firefox-extension.zip
