name: tests
permissions:
  contents: read

on:
  pull_request:
    branches:
      - main

jobs:
  detect-license-changes:
    runs-on: ubuntu-latest
    outputs:
      licenses: ${{ steps.filter.outputs.licenses }}
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            licenses:
              - 'package.json'
              - 'package-lock.json'

  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Use Node.js 22.x
        uses: actions/setup-node@v5
        with:
          node-version: 22
          cache: 'npm'
      - name: Install npm deps
        run: npm ci
      - name: Prettier formatting
        run: npm run prettier:check

  lint:
    runs-on: ubuntu-latest
    needs: format
    steps:
      - uses: actions/checkout@v5
      - name: Use Node.js 22.x
        uses: actions/setup-node@v5
        with:
          node-version: 22
          cache: 'npm'
      - name: Install npm deps
        run: npm ci
      - name: Lint
        run: npm run lint

  build-chrome:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v5
      - name: Use Node.js 22.x
        uses: actions/setup-node@v5
        with:
          node-version: 22
          cache: 'npm'
      - name: Install npm deps
        run: npm ci
      - name: Build extension for Chrome
        run: npm run build
      - name: Zip Chrome build output
        run: |
          cd build
          zip -r ../icloud-hide-my-email-plus-chrome-extension.zip .
      - name: Upload Chrome artifact
        uses: actions/upload-artifact@v4
        with:
          name: icloud-hide-my-email-plus-chrome-extension
          path: icloud-hide-my-email-plus-chrome-extension.zip

  build-firefox:
    runs-on: ubuntu-latest
    needs: build-chrome
    steps:
      - uses: actions/checkout@v5
      - name: Use Node.js 22.x
        uses: actions/setup-node@v5
        with:
          node-version: 22
          cache: 'npm'
      - name: Install npm deps
        run: npm ci
      - name: Build extension for Firefox
        # This also lints the Firefox build using web-ext.
        # In the future add -w to the lint to treat warnings as errors.
        run: |
          npm run build:firefox
          npx web-ext lint --source-dir build
          npx web-ext build --source-dir build --artifacts-dir . --filename icloud-hide-my-email-plus-firefox-extension.zip
      - name: Upload Firefox artifact
        uses: actions/upload-artifact@v4
        with:
          name: icloud-hide-my-email-plus-firefox-extension
          path: icloud-hide-my-email-plus-firefox-extension.zip

  license-audit:
    needs: detect-license-changes
    if: needs.detect-license-changes.outputs.licenses == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Use Node.js 22.x
        uses: actions/setup-node@v5
        with:
          node-version: 22
          cache: 'npm'
      - name: Install npm deps
        run: npm ci
      - name: Check dependency licenses
        run: npm run check:licenses -- --verbose

  attribution-check:
    needs: detect-license-changes
    if: needs.detect-license-changes.outputs.licenses == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Use Node.js 22.x
        uses: actions/setup-node@v5
        with:
          node-version: 22
          cache: 'npm'
      - name: Install npm deps
        run: npm ci
      - name: Ensure ATTRIBUTIONS.md is up to date
        run: |
          npm run report:licenses
          if ! git diff --quiet ATTRIBUTIONS.md; then
            echo "::error::ATTRIBUTIONS.md is out of date. Run 'npm run report:licenses' and commit the result.";
            git diff -- ATTRIBUTIONS.md;
            exit 1;
          fi
