name: tests

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Use Node.js 18.x
        uses: actions/setup-node@v5
        with:
          node-version: 18
          cache: 'npm'
      - name: Install npm deps
        run: npm ci
      - name: Prettier formatting
        run: npm run prettier:check
      - name: Lint
        run: npm run lint
      - name: Build extension
        run: npm run build
