name: tests
permissions:
  contents: read

on:
  pull_request:
    branches:
      - main

jobs:
  detect-license-changes:
    runs-on: ubuntu-latest
    outputs:
      licenses: ${{ steps.filter.outputs.licenses }}
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            licenses:
              - 'package.json'
              - 'package-lock.json'

  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Use Node.js 22.x
        uses: actions/setup-node@v5
        with:
          node-version: 22
          cache: 'npm'
      - name: Install npm deps
        run: npm ci
      - name: Prettier formatting
        run: npm run prettier:check

  lint:
    runs-on: ubuntu-latest
    needs: format
    steps:
      - uses: actions/checkout@v5
      - name: Use Node.js 22.x
        uses: actions/setup-node@v5
        with:
          node-version: 22
          cache: 'npm'
      - name: Install npm deps
        run: npm ci
      - name: Lint
        run: npm run lint

  build-brave:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v5
      - name: Use Node.js 22.x
        uses: actions/setup-node@v5
        with:
          node-version: 22
          cache: 'npm'
      - name: Install npm deps
        run: npm ci
      - name: Package Brave bundle
        run: |
          npm run package:brave
          ZIP_WITH_VERSION=$(find build -maxdepth 1 -name 'icloud-hide-my-email-plus-browser-extension-*-brave.zip' -print -quit)
          if [ -z "$ZIP_WITH_VERSION" ]; then
            echo "::error::Unable to find Brave package output";
            exit 1;
          fi
          mv "$ZIP_WITH_VERSION" build/icloud-hide-my-email-plus-browser-extension-brave.zip
      - name: Upload Brave artifact
        uses: actions/upload-artifact@v4
        with:
          name: icloud-hide-my-email-plus-browser-extension-brave
          path: build/icloud-hide-my-email-plus-browser-extension-brave.zip

  build-chrome:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v5
      - name: Use Node.js 22.x
        uses: actions/setup-node@v5
        with:
          node-version: 22
          cache: 'npm'
      - name: Install npm deps
        run: npm ci
      - name: Package Chrome bundle
        run: |
          npm run package:chrome
          ZIP_WITH_VERSION=$(find build -maxdepth 1 -name 'icloud-hide-my-email-plus-browser-extension-*-chrome.zip' -print -quit)
          if [ -z "$ZIP_WITH_VERSION" ]; then
            echo "::error::Unable to find Chrome package output";
            exit 1;
          fi
          mv "$ZIP_WITH_VERSION" build/icloud-hide-my-email-plus-browser-extension-chrome.zip
      - name: Upload Chrome artifact
        uses: actions/upload-artifact@v4
        with:
          name: icloud-hide-my-email-plus-browser-extension-chrome
          path: build/icloud-hide-my-email-plus-browser-extension-chrome.zip

  build-edge:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v5
      - name: Use Node.js 22.x
        uses: actions/setup-node@v5
        with:
          node-version: 22
          cache: 'npm'
      - name: Install npm deps
        run: npm ci
      - name: Package Edge bundle
        run: |
          npm run package:edge
          ZIP_WITH_VERSION=$(find build -maxdepth 1 -name 'icloud-hide-my-email-plus-browser-extension-*-edge.zip' -print -quit)
          if [ -z "$ZIP_WITH_VERSION" ]; then
            echo "::error::Unable to find Edge package output";
            exit 1;
          fi
          mv "$ZIP_WITH_VERSION" build/icloud-hide-my-email-plus-browser-extension-edge.zip
      - name: Upload Edge artifact
        uses: actions/upload-artifact@v4
        with:
          name: icloud-hide-my-email-plus-browser-extension-edge
          path: build/icloud-hide-my-email-plus-browser-extension-edge.zip

  build-firefox:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v5
      - name: Use Node.js 22.x
        uses: actions/setup-node@v5
        with:
          node-version: 22
          cache: 'npm'
      - name: Install npm deps
        run: npm ci
      - name: Package Firefox bundle
        run: |
          npm run package:firefox
          ZIP_WITH_VERSION=$(find build -maxdepth 1 -name 'icloud-hide-my-email-plus-browser-extension-*-firefox.zip' -print -quit)
          if [ -z "$ZIP_WITH_VERSION" ]; then
            echo "::error::Unable to find Firefox package output";
            exit 1;
          fi
          mv "$ZIP_WITH_VERSION" build/icloud-hide-my-email-plus-browser-extension-firefox.zip
      - name: Lint Firefox bundle
        run: npx web-ext lint --source-dir build
      - name: Upload Firefox artifact
        uses: actions/upload-artifact@v4
        with:
          name: icloud-hide-my-email-plus-browser-extension-firefox
          path: build/icloud-hide-my-email-plus-browser-extension-firefox.zip

  license-audit:
    needs: detect-license-changes
    if: needs.detect-license-changes.outputs.licenses == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Use Node.js 22.x
        uses: actions/setup-node@v5
        with:
          node-version: 22
          cache: 'npm'
      - name: Install npm deps
        run: npm ci
      - name: Check dependency licenses
        run: npm run check:licenses -- --verbose

  attribution-check:
    needs: detect-license-changes
    if: needs.detect-license-changes.outputs.licenses == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Use Node.js 22.x
        uses: actions/setup-node@v5
        with:
          node-version: 22
          cache: 'npm'
      - name: Install npm deps
        run: npm ci
      - name: Ensure ATTRIBUTIONS.md is up to date
        run: |
          npm run report:licenses
          if ! git diff --quiet ATTRIBUTIONS.md; then
            echo "::error::ATTRIBUTIONS.md is out of date. Run 'npm run report:licenses' and commit the result.";
            git diff -- ATTRIBUTIONS.md;
            exit 1;
          fi
